In [270]:
import pandas as pd
from sklearn.datasets import make_moons

In [271]:
def process_data(df, categorical_cols, numeric_cols):

    # One-Hot Encoding
    df_processed = pd.get_dummies(df, columns=categorical_cols, drop_first=False)

    for col in df_processed.columns:
        if df_processed[col].dtype == 'bool':
            df_processed[col] = df_processed[col].astype(int)

    #CDF
    for col in numeric_cols:
        df_processed[col] = df_processed[col].rank() / len(df_processed)

    return df_processed

**Insurance**<br>
Num: 4 Cat: 3

In [272]:
df_insurance = pd.read_csv('data/original/insurance.csv')

len(df_insurance)

1338

In [273]:
df_insurance.isna().sum(axis=0)

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [294]:
df_insurance.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [275]:
categorical_cols = ['sex', 'smoker', 'region']
numeric_cols = ['age', 'bmi', 'children', 'expenses']

df_processed = process_data(df_insurance, categorical_cols, numeric_cols)
df_processed.head()

,age,bmi,children,expenses,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,0.077354,0.345665,0.214873,0.752616,1,0,0,1,0,0,0,1
1,0.026158,0.707025,0.550448,0.044096,0,1,1,0,0,0,1,0
2,0.281390,0.655830,0.909567,0.230194,0,1,1,0,0,0,1,0
3,0.381540,0.092676,0.214873,0.821375,0,1,1,0,0,1,0,0
4,0.362108,0.407698,0.214873,0.191330,0,1,1,0,0,1,0,0

In [276]:
df_processed.shape

(1338, 12)

In [277]:
df_processed.to_csv('data/processed/insurance.csv', index=False)

**Abalone**<br>
Num: 7 Cat: 2

In [278]:
df_abalone = pd.read_csv('data/original/abalone.csv')

len(df_abalone)

4177

In [279]:
df_abalone.isna().sum(axis=0)

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weight    0
Viscera weight    0
Shell weight      0
Rings             0
dtype: int64

In [295]:
df_abalone.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,1
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,0
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,0
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,0
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,0

In [281]:
df_abalone['Rings'] = (df_abalone['Rings'] > 10).astype('int') #Не уверен, что именно поэтому с этим датасетом решалась бинарная классификация.

In [282]:
df_abalone.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,1
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,0
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,0
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,0
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,0

In [283]:
categorical_cols = ['Sex']
numeric_cols = ['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight']

df_processed = process_data(df_abalone, categorical_cols, numeric_cols)
df_processed.head()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings,Sex_F,Sex_I,Sex_M
0,0.260713,0.303088,0.139813,0.304405,0.318410,0.273402,0.300215,1,0,0,1
1,0.093967,0.097678,0.114077,0.116711,0.122456,0.114676,0.113000,0,0,0,1
2,0.464209,0.486114,0.428777,0.421475,0.372636,0.403878,0.447690,0,1,0,0
3,0.227915,0.303088,0.341513,0.306679,0.303687,0.316734,0.313981,0,0,0,1
4,0.075054,0.083792,0.072420,0.100072,0.104142,0.087742,0.080201,0,0,1,0

In [284]:
df_processed.shape

(4177, 11)

In [285]:
df_processed.to_csv('data/processed/abolone.csv', index=False)

**Two moons**<br>
Num: 2 Cat: 1

In [ ]:
X, y = make_moons(n_samples=40000, random_state=42)# В статье обозначена этот датасет как синтетический

df_moons = pd.DataFrame(X, columns=['x1', 'x2'])
df_moons['label'] = y

len(df_moons)

40000

In [287]:
df_moons.head()

         x1        x2  label
0  1.429136 -0.403240      1
1 -0.835705  0.549178      0
2  0.767383 -0.472569      1
3  0.496913  0.867800      0
4  0.531147 -0.383276      1

In [288]:
df_moons.isna().sum(axis=0)

x1       0
x2       0
label    0
dtype: int64

In [289]:
categorical_cols = []
numeric_cols = ['x1', 'x2']

df_processed = process_data(df_moons, categorical_cols, numeric_cols)
df_processed.head()

         x1        x2  label
0  0.820600  0.141175      1
1  0.092550  0.685100      0
2  0.601875  0.074750      1
3  0.498875  0.834475      0
4  0.511475  0.155350      1

In [290]:
df_processed.shape

(40000, 3)

In [291]:
df_processed.head()

         x1        x2  label
0  0.820600  0.141175      1
1  0.092550  0.685100      0
2  0.601875  0.074750      1
3  0.498875  0.834475      0
4  0.511475  0.155350      1

In [292]:
df_moons.to_csv('data/original/two_moons.csv', index=False)
df_processed.to_csv('data/processed/two_moons.csv', index=False)